### ISSUE TITLE
Background gray and not loading as of a few days ago

### ISSUE THREAD

**Issue by Skyyblaze** [DamianSowinski/whatsapp#3]
As of a few days ago my custom background-image for the style just shows up as a solid gray color. I confirmed the image itself still works and is available when I directly access the URL so WhatsApp must have messed with things again. Could this be looked into?

**Comment by DamianSowinski** [comment]
Hi, fixed, please check.

**Comment by DamianSowinski** [comment]
1. Please use online image to base64 converter (eg https://www.base64-image.de ) to convert your image into encoded text
2. Copy generated encoded text and paste here inside single quote mark eg `'data:image/jpeg;base64,/9j/4A....'`
![obraz](https://github.com/DamianSowinski/whatsapp/assets/44449915/4fae93fa-8c9c-4739-9bd7-6fdc1cb13df0)

**Notice:** 
- compress your image before encode it to base64
- copied encoded text is quite big - after paste it into input field the browser may freeze for a while and pasted text will not be showed immediately, please wait.
